export declare class APIService {
    private readonly serviceName;
    constructor(serviceName: string);
    readonly name: string;
}
declare const APIMapping: {
    aclGroupService: APIService;
    adminTokenService: APIService;
    agentRecommendationService: APIService;
    appointmentBookingService: APIService;
    behaviourService: APIService;
    caasManamgentService: APIService;
    cognitoClientService: APIService;
    commissionCalculationService: APIService;
    companyService: APIService;
    componentService: APIService;
    contactService: APIService;
    customerLegitimationArchiveService: APIService;
    dynamicLayoutService: APIService;
    emailService: APIService;
    entityExportService: APIService;
    entityService: APIService;
    excelExporterService: APIService;
    flowfactExporterInternalService: APIService;
    flywheelService: APIService;
    formService: APIService;
    fullTextSearchService: APIService;
    funnelService: APIService;
    gdprService: APIService;
    geolocationService: APIService;
    importPreparationService: APIService;
    importerFlowFactTransferService: APIService;
    inquiryService: APIService;
    interactiveExposeDeliveryService: APIService;
    interactiveExposeService: APIService;
    interactiveExposeStatisticsService: APIService;
    matchmakingService: APIService;
    moduleService: APIService;
    nylasService: APIService;
    nylasContactSyncService: APIService;
    multimediaService: APIService;
    office365AuthenticationService: APIService;
    portalManagementService: APIService;
    presetService: APIService;
    propertyMarketingPhaseService: APIService;
    relogService: APIService;
    sampleDataService: APIService;
    schemaService: APIService;
    searchService: APIService;
    slackIntegrationService: APIService;
    spregnetterService: APIService;
    taggingService: APIService;
    tagService: APIService;
    templateService: APIService;
    trialLicenseServive: APIService;
    userService: APIService;
    viewDefinitionService: APIService;
    historyModuleService: APIService;
    onboardingService: APIService;
    csvToEntityImporterService: APIService;
    omniChannelService: APIService;
    clientNotificationService: APIService;
    is24PublishService: APIService;
    is24EntitlementService: APIService;
    filterDefinitionService: APIService;
    contractService: APIService;
    softLinksEntityService: APIService;
    openimmoFtpAccessService: APIService;
    openimmoImporterService: APIService;
    workflowService: APIService;
    searchProfileService: APIService;
    is24ImportService: APIService;
};
export default APIMapping;
